### ISSUE TITLE
deprecation warning about mergeOptions

### ISSUE THREAD

**Issue by bwaindwain** [videojs/videojs-playlist-ui#148]
## Description
Using this plugin with videojs 8.0.4, the console shows a warning:

> VIDEOJS: WARN: videojs.mergeOptions is deprecated and will be removed in 9.0; please use videojs.obj.merge instead.

## Steps to reproduce
Explain in detail the exact steps necessary to reproduce the issue.

1. use videojs 8.0.4
2. load a player with a playlist

#### videojs
8.0.4

#### browsers
Chrome 112, Firefox 112

### plugins
videojs_playlist 5.0.1
videojs_playlist_ui 4.1.1

Same as https://github.com/videojs/videojs-contrib-quality-levels/pull/138

**Comment by misteroneill** [comment]
This should be resolved as of 4.2.0, thanks for the report!
